title: Eric Miranda
description: Fourth-year at UC San Diego, with a passion for software engineering and UI/UX design. I am an aspiring Cognitive Scientist driven by the continuous advancements and potential use of complex algorithms that shape our daily lives.
theme: just-the-docs

url: https://emiranda0.github.io

aux_links:
  Github Repository: https://github.com/emiranda0
  
 